development:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 12345
  database: directory

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 12345
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 12345
  database: db/production.sqlite3
